# Generated by Django 5.1.4 on 2025-08-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('observer', 'Observador')], default='observer', max_length=140),
        ),
    ]
