# Generated by Django 5.1.4 on 2025-09-08 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_options_and_more'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentstation',
            options={'verbose_name': 'equipment', 'verbose_name_plural': 'equipments'},
        ),
        migrations.AlterModelOptions(
            name='rainfallstation',
            options={'verbose_name': 'rainfall', 'verbose_name_plural': 'rainfalls'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'station', 'verbose_name_plural': 'stations'},
        ),
        migrations.AlterField(
            model_name='equipmentstation',
            name='brand',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='equipmentstation',
            name='code',
            field=models.CharField(max_length=140, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='equipmentstation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='equipmentstation',
            name='model',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='equipmentstation',
            name='name',
            field=models.CharField(max_length=140, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='equipmentstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.station', verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='rainfallstation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='rainfallstation',
            name='day',
            field=models.IntegerField(default=0, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='rainfallstation',
            name='month',
            field=models.IntegerField(default=0, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='rainfallstation',
            name='registration_date',
            field=models.DateField(verbose_name='registration_date'),
        ),
        migrations.AlterField(
            model_name='rainfallstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.station', verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='rainfallstation',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='rainfallstation',
            name='year',
            field=models.IntegerField(default=0, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(max_length=140, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='station',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=140, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='station',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='organization'),
        ),
    ]
