# Generated by Django 5.1.4 on 2025-08-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('country', 'País'), ('department', 'Departamento'), ('municipality', 'Municipio'), ('communnity', 'Comunidad')], default='country', max_length=140),
        ),
    ]
