name: Quick Tests

on:
  workflow_dispatch: # Permite ejecutar manualmente
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'pytest.ini'

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up environment variables
      run: |
        echo "SECRET_KEY=test-secret-key-for-github-actions" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV
        echo "DATABASE=sqlite" >> $GITHUB_ENV
    
    - name: Run Django migrations
      run: |
        python manage.py migrate
    
    - name: Run tests with pytest (unit tests only)
      run: |
        pytest -m "not slow and not integration" --tb=short
