# Generated by Django 5.1.4 on 2025-09-08 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
        ('stations', '0002_alter_equipmentstation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rainfallhistory',
            options={'verbose_name': 'historical', 'verbose_name_plural': 'historical'},
        ),
        migrations.AlterField(
            model_name='rainfallhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='rainfallhistory',
            name='month',
            field=models.IntegerField(default=0, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='rainfallhistory',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.station', verbose_name='station'),
        ),
        migrations.AlterField(
            model_name='rainfallhistory',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='value'),
        ),
    ]
